package pojos;

import java.io.Serializable;

public class BookPOJO implements Serializable {
private int bookId;//unique Identifier
private String title,author;
private double price;
//if ID generator : assigned => ID has to be generated by the appln
//prog . But if ID generator - increment : ID will be gener. by
//hib frmwork.
public BookPOJO(String title, String author, double price) {
	super();
	this.title = title;
	this.author = author;
	this.price = price;
}
public BookPOJO() {
	// TODO Auto-generated constructor stub
}
public int getBookId() {
	return bookId;
}
public void setBookId(int bookId) {
	this.bookId = bookId;
}
public String getTitle() {
	return title;
}
public void setTitle(String title) {
	this.title = title;
}
public String getAuthor() {
	return author;
}
public void setAuthor(String author) {
	this.author = author;
}
public double getPrice() {
	return price;
}
public void setPrice(double price) {
	this.price = price;
}
@Override
public String toString() {
	return "BookPOJO [author=" + author + ", bookId=" + bookId + ", price="
			+ price + ", title=" + title + "]";
}


}
